### ISSUE TITLE
Scrolling past terminal page view's laggy (optimize re-rendering)

### ISSUE THREAD

**Issue by brian6932** [YS-L/csvlens#107]
When you scroll up or down past the current terminal page view, the scroll feels very laggy and sluggish. So much so, that if you hold `j`/`k` for long enough, you'll have to wait until the rendering's finished to do anything at all. The csv I was looking at only has 4 columns, so it's not exactly much to parse and render, but it's slow. I understand that when the page changes, you have to re-render most elements, however, stuff like the column count with it's respective tabulation, and csv headers don't need to be re-rendered, and from what I'm seeing by the column & line boundaries shifting around, they're being re-rendered (line column size should just be pre-allocated by the newline count for example). There are loads of TUI programs that despite needing to re-render portions of the page, have some decent buffering, and/or good strategies to minimize rendering to where there's no scroll lag (e.g. [heh](https://github.com/ndd7xv/heh), [gonk](https://github.com/zX3no/gonk), [bottom](https://github.com/ClementTsang/bottom)).

**Comment by YS-L** [comment]
Thanks for reporting this! From my understanding, Ratatui uses a diffing algorithm between frame buffers to ensure efficient writing to the terminal screen, so I’m not sure if re-rendering is the cause of the sluggishness.

Would you be able to share a CSV file along with the steps (any filters or sorting applied) to reproduce this issue? I think with that and some profiling, we can narrow down the cause.

**Comment by brian6932** [comment]
>Would you be able to share a CSV file

[Sure](https://github.com/user-attachments/files/17443855/test.csv)

>any filters or sorting applied

Nothing, everything's stock

**Comment by YS-L** [comment]
Thanks! It would be great if you could run csvlens with the `--debug` flag, ideally on the main branch, as this will display some debugging stats related to rendering time. Using your CSV file, I’m getting something like this:

![image](https://github.com/user-attachments/assets/26b86699-81eb-456d-abf3-ddd0756f0ed9)

I'm curious what the numbers look like in your case, especially the number after `render` when scrolling past the page.

**Comment by YS-L** [comment]
I might have a theory about the cause of the slowness - unbuffered stderr. It would be great if you can test whether https://github.com/YS-L/csvlens/pull/110 fixes the issue in your case.

**Comment by brian6932** [comment]
Yes #110 is much better, fixes this issue. Only thing that's still a bit jarring to me, and possibly hurts rendering performance's that it seems like columns are dynamically sized, depending on the csv this makes sense to me, but it might be good to have a flag which allows you to toggle between preallocated csv columns, and growing ones maybe.
![](https://github.com/user-attachments/assets/adb1aac1-064e-4ed0-b4d3-1f81faba804e)
