### ISSUE TITLE
Bug in Row implementation with regex matching

### ISSUE THREAD

**Issue by antmelon** [YS-L/csvlens#111]
Performing a row filter with a regex that does not exist in CSV file will panic and crash

```rs
impl Row {
    pub fn subset(&self, indices: &[usize]) -> Row {
        let mut subfields = vec![];
        for i in indices {
            subfields.push(self.fields.get(*i).unwrap().clone());
        }
        Row {
            record_num: self.record_num,
            fields: subfields,
        }
    }

    fn empty() -> Row {
        Row {
            record_num: 0,
            fields: vec![],
        }
    }
}
```

the for loop in `subset` will try to unwrap a None value and crash

**Comment by YS-L** [comment]
The `subset` method is intended for filtering columns rather than rows. The indices used are generated here:

https://github.com/YS-L/csvlens/blob/29e46af3921867097ed09d746dd80d57676b9aad/src/view.rs#L41-L51

This logic ensures the indices are always valid.

Applying a row filter doesn't trigger these code paths. Have you been able to reproduce the panic? Sharing a traceback could help identify any underlying cause.

**Comment by antmelon** [comment]
The issue happens when there are rows with different numbers of columns. 
[foo.csv](https://github.com/user-attachments/files/17556859/foo.csv)

When filtering on a column that is present for all rows, there are no issues. When filtering on a column that is either out of bounds of some rows, or not present in any, the following error is received:

```
thread 'main' panicked at /home/alongo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/csvlens-0.10.1/src/csv.rs:96:48:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The change made in #112 resolves this issue and allows filtering on all columns. If the column is not present in any row, it functions as normal and continues to show all columns

**Comment by YS-L** [comment]
Got it, thanks for clarifying! Support for irregular CSV files is handled on a best-effort basis, and #112 is definitely an improvement that smooths out a rough edge. Much appreciated!
