### ISSUE TITLE
TSV delimiter

### ISSUE THREAD

**Issue by darked89** [YS-L/csvlens#19]
Hello,

would it be possible to handle TSV files as well?

I did:
```
csvlens -d "\t"  data_timepoints.tsv

# error:
Delimiter should be exactly one character, got \t
```
Thank you

DK

**Comment by YS-L** [comment]
Yes, you can specify the delimiter using the `-d` flag. Have you tried  `csvlens -d \t  data_timepoints.tsv` (without the double quotes) instead?

**Comment by YS-L** [comment]
Correction: the correct command to use is

```bash
csvlens -d $'\t' data_timepoints.tsv
```

in order to specify the literal tab character correctly in the command line. Alternatively, the main branch now supports an option `-d auto` to auto-detect the delimiter.
