### ISSUE TITLE
Feature Request: More `less`-like key bindings

### ISSUE THREAD

**Issue by jqnatividad** [YS-L/csvlens#32]
As csvlens is patterned after `less`, some other `less` key bindings to consider:
* Home, End keys to go to top/bottom of CSV respectively
* ^RightArrow - Right to last column
* ^LeftArrow - Left to first column
* h key for Help Screen showing key bindings

**Comment by arildm** [comment]
- `d` Down half a page
- `u` Up half a page
- `h` Show help page with key bindings

**Comment by YS-L** [comment]
Thanks for the suggestions! These are now added in v0.4.0.
