### ISSUE TITLE
Feature request: Sorting

### ISSUE THREAD

**Issue by da2r-20** [YS-L/csvlens#35]
First of all great project!
Is it possible to add a sorting per-column (regular sort and natural)

**Comment by YS-L** [comment]
Hello! For now I intended csvlens to be a simple viewer / pager, so sorting seems a bit out of scope. Would using other tools such as [qsv](https://github.com/jqnatividad/qsv) for sorting and then piping to csvlens work for your case?

**Comment by kleinmatic** [comment]
Just wanted to add a quick upvote to the idea of column sorting. It would very much increase the utility of this, which is already great! I often open csv's to do some quick data-distribution assessments, which is to say, I look for column min/maxes. 

Thanks for making this!

**Comment by YS-L** [comment]
Thanks for the suggestions! I can see the value of being able to do sorting interactively. I added an experimental sorting option in the main branch (key binding: `Shift + ↓`  or `Shift + j`). Feel free to try it and let me know what you think!
