### ISSUE TITLE
Resize columns

### ISSUE THREAD

**Issue by SOF3** [YS-L/csvlens#37]
While I can do `-S`, it would be better if I could just increase the column width directly.

Probably a separate feature, but it would be useful to be able to preview a collapsed cell instead of having to echo it.

**Comment by YS-L** [comment]
Thanks for the suggestions! Ability to resize columns directly makes sense and is in my backlog.

Could you elaborate a bit more on previewing a collapsed cell? An example or screenshot would be great.

**Comment by SOF3** [comment]
Currently the only way to view the content of an overflowing cell is to press `enter` and view it in stdout, but that stops `csvlens`. Would prefer if I could view it directly without quitting.

**Comment by YS-L** [comment]
Added support for manual column resize in v0.4.0 (using keys `<` or `>`).
