### ISSUE TITLE
Feature Request: column-/row- filter as command line parameter

### ISSUE THREAD

**Issue by kajdo** [YS-L/csvlens#41]
This is a fantastic tool --- 1000x thx - very well done

would love to see the posibility to add a column filter directly via start parameter, so i can alias some common checks

example
1) csvlens income.csv
2) "*" for column filter
3) type ^Rev* as regex
4) enter

vs.
1) csvlens -column_filter:"^Rev*" income.csv
2) happy

just an idea

**Comment by YS-L** [comment]
Thanks for the suggestion! I think it makes sense to have such options.

Are you looking at changing the filter interactively when viewing the file? If not, one alternative that is possible now is to process the file with tools such as [`qsv`](https://github.com/jqnatividad/qsv) first before piping it to csvlens:

```
qsv select '/^Rev*/' income.csv | csvlens
```

**Comment by YS-L** [comment]
Added `--columns`, `--filter`, and `--find` options in v0.7.0.
