### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by kishaningithub** [YS-L/csvlens#43]
Can this be made available as a homebrew package?

**Comment by YS-L** [comment]
Hi @kishaningithub, definitely. Will look into this.

**Comment by madhur** [comment]
Need AUR package as well for Arch Linux

**Comment by madhur** [comment]
I have published AUR package
https://aur.archlinux.org/packages/csvlens

Pls check it out @YS-L

**Comment by kishaningithub** [comment]
I don't know much about AUR packages but one question I have is why so many dependencies(Screenshot below)? Given rust can produce a statically linked binary can AUR not pull the platform specific binary from GitHub releases and publish it, that way dependencies would be zero.

![Screenshot_2024-01-06-07-56-29-15_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/YS-L/csvlens/assets/763760/1cd577bc-394c-497d-8746-2069ab100662)

**Comment by hyiltiz** [comment]
AUR packages are not maintained by Archlinux [1], and is typically provided as source packages to be built locally, with the expectation that users should do the due diligence themselves to validate the safety of the packages they install. If a package is submitted into Archlinux (or Debian) as a binary package, it should be possible to ship the release binary itself, separating the build dependencies from runtime dependencies.

https://wiki.archlinux.org/title/Arch_User_Repository

**Comment by YS-L** [comment]
csvlens is now available on homebrew: https://formulae.brew.sh/formula/csvlens

**Comment by YS-L** [comment]
Thanks @madhur for the AUR package!
