### ISSUE TITLE
Lower level causes should be printed on error

### ISSUE THREAD

**Issue by sgryjp** [YS-L/csvlens#45]
Would you consider to let csvlens print lower level causes on exiting with an error?

As of v0.5.0, csvlens does not print lower level causes stored in an `anyhow::Error` instance on error exit. This means that the error message is not very helpful as the root cause is not reported to users. For example, trying to open a non-existent file and trying to open an existing but not UTF-8 encoded file emits completely same message:

```sh
$ echo "亜" | iconv -f utf-8 -t cp932 > cp932.csv
$ csvlens cp932.csv
Failed to open file: cp932.csv
$ csvlens no-such-file.csv
Failed to open file: no-such-file.csv
```

Since an `anyhow::Error` instance [contains lower level causes and provides some ways to extract them](https://docs.rs/anyhow/1.0.56/anyhow/struct.Error.html#display-representations), using one of them should solve the situation.

**Comment by YS-L** [comment]
Hi @sgryjp, yes that makes a lot of sense. Thanks for the suggestion!
