### ISSUE TITLE
Rendering problems when run inside gnu screen

### ISSUE THREAD

**Issue by Heeten** [YS-L/csvlens#56]
When I use csvlens (which is awesome!) inside a gnu screen session it seems like it doesn't render fully and I end up with part of the output from csvlens mashed with part of what was displayed in my terminal before.

Everything works great if I use a vanilla terminal window. I'm able to use `less -S` and other terminal windows fine in gnu screen.

**Comment by YS-L** [comment]
Do you have alternative screen support enabled in your gnu screen config? It's required by csvlens for proper rendering.

For example: https://stackoverflow.com/questions/17868652/screen-how-to-turn-on-alternate-screen

**Comment by Heeten** [comment]
Ah I didn't have that on. I set it and now csvlens is working better although it doesn't exactly match the rendering when I'm not in screen. It's functionally though which wasn't the case without that setting. Thank you!
