### ISSUE TITLE
Support CSV without header row

### ISSUE THREAD

**Issue by svenvanhal** [YS-L/csvlens#60]
Sometimes, I'm dealing with CSV files that don't have headings. csvlens now always takes the first row as header row.
I'd like modify this behavior with a command line flag, something like `--no-header` to treat all rows as data.

(awesome tool btw!)

**Comment by jobm** [comment]
I'll try to work on this one.

**Comment by YS-L** [comment]
Added `--no-headers` option in the main branch. Thanks for the suggestion!
