### ISSUE TITLE
Broken build on termux

### ISSUE THREAD

**Issue by phanirithvij** [YS-L/csvlens#70]
On termux (Android aarch64) csvlens used to work but the new clipboard change breaks the build due to https://github.com/1Password/arboard/issues/113 no termux support.

**Comment by YS-L** [comment]
Thanks for reporting! I could make clipboard a features that can be opted out with `--no-default-features` when building. 

Would that work in your case? Here's a PR to test: https://github.com/YS-L/csvlens/pull/71
