### ISSUE TITLE
Rendering problems w/ irregular columns

### ISSUE THREAD

**Issue by hxx-fetch** [YS-L/csvlens#73]
Hi,

with data like this:
```
COL1, COL2
c1
c2, v2
c2, 4,
c3
c4
c5
c7
c9
c10
c11
c12
c13
c14,2
```

and a small terminal window, which forces up/down scrolling the rendering has problems
(kdeterm or xterm). The right table line appears BEFORE the second column. When scrolling down 
at some point the problem disappears and the the right line show AFTER the second column.

When I ensure all lines have the same number of fields, everything is fine as well.

Micha

**Comment by YS-L** [comment]
Hi! Support for irregular columns is on a best effort basis. Most of the functionalities assume that the columns are regular and might not work otherwise. That said, it should be possible to handle this with relatively simple changes.
