### ISSUE TITLE
How to find the first empty / not-empty row?

### ISSUE THREAD

**Issue by szabgab** [YS-L/csvlens#76]
It took me a while but finally I figured out that in order to find the first row where a given column is not empty can be done by switching to column-selection mode using `TAB` and then pressing `/` and searching for `.` that should match any character.

I still could not figure out though how to find the first row where a given column is empty?
Is it possible? If not, maybe there could a negated regex search eg. `!/<regex>` would search for rows not matching the regex.

**Comment by YS-L** [comment]
You can try searching using this regex: `^$`

It should find the empty strings, though the highlighting probably won't work well because there's no text to highlight in this case.

**Comment by YS-L** [comment]
And yes, searching using column selection mode will constrain the search to a particular column. I was hoping that this would be intuitive, but the documentation can definitely be improved.

**Comment by szabgab** [comment]
Thanks. When you refer to documentation do you mean the help page, the README in the git repository or something else (that I have not found yet)?

**Comment by YS-L** [comment]
I was referring to the README and the in app help page. That's all there is to it for now!
