### ISSUE TITLE
& and * on Windows?

### ISSUE THREAD

**Issue by amreus** [YS-L/csvlens#82]
When typing `/` I get prompted for the regex to search for. 

I also expected to be prompted for a regex when typing `&` or `*` but nothing appears to happen. Do I misunderstand how to use the filter functions?

Thanks.

**Comment by YS-L** [comment]
Your understanding is correct - typing `&` or `*` should show a prompt for regex as well. Curious if there are other key bindings that don't work as expected or are these the only two?

If you could share a bit more information about your system that could be helpful.

**Comment by amreus** [comment]
✔️ `Tab` for changing modes. 
✔️ `hjkl` works for navigation in all modes.
✔️ `ctrl-f` & `ctr-b`
✔️ `ctrl-u` & `ctrl-d`
✔️ `G' & `g`
✔️ `<n>G` goto line

✔️ `/` for searching prompt
✔️ `n` & `N`
❌ `&` and `*` for filtering don't appear to do anything

**Comment by YS-L** [comment]
Thanks for the detailed report! I will get to this once I have access to a Windows machine to test and reproduce.

**Comment by amreus** [comment]
I'm willing to run test versions if it would help. I can also compile and test from a test branch of the repo.  I'm no programmer, but let me know it I can help.

**Comment by YS-L** [comment]
@amreus Thank you! Based on the symptoms I suspect the issue is related to shift key handling in Windows. I have a possible fix in https://github.com/YS-L/csvlens/pull/84. It would be great if you can test if it works.

**Comment by amreus** [comment]
Works 100%, thank you. This is a wonderful tool. And thank you for considering Windows a worthwhile platform - many projects unfortunately do not.

**Comment by YS-L** [comment]
This has been very helpful, thank you!
