### ISSUE TITLE
Feature request: Sorting Descending

### ISSUE THREAD

**Issue by paulmwatson** [YS-L/csvlens#86]
Very useful project as I work through millions of rows of South African 2024 election results. Thank you for adding (sorting)[https://github.com/YS-L/csvlens/issues/35]. 

I see it is ascending only:
> I added an experimental sorting option in the main branch (key binding: Shift + ↓ or Shift + j)

Can descending sorting be added please?

I will look at the code and see if I'm up to changing Rust and then will submit a PR.

**Comment by YS-L** [comment]
Definitely! I wanted to keep it simple so it's currently ascending only, but it makes sense to support descending order as well.

**Comment by YS-L** [comment]
Sorting by descending order is now supported in the main branch. You can use the same key binding `Shift + ↓` (or `Shift + j`) to toggle sort direction.
