### ISSUE TITLE
Option: expand to full-width

### ISSUE THREAD

**Issue by plutonium-239** [YS-L/csvlens#88]
In #11, it was discussed that columns don't take up full-width by default, and that's fine. However, I would love the addition of a keybind that automatically expands the table (could be multiple truncated columns) to full-width.
Take this example use case:
> Have a 3 (arbitrary) column csv of sentences (say original, translation, transliteration), then I would like all three of these columns to be equally divided into columns of `full-width/3`

Is something like this feasible?

**Comment by YS-L** [comment]
Thanks for the suggestion! This makes sense and should be feasible, though I'm wondering if this should be a key binding or something that should happen automatically.

Ideally, csvlens should take up full width if that doesn't reduce the number of columns that can be displayed. The current column widths heuristic optimizes for CSV with many columns, but probably not so much for CSV with few columns and long text.

**Comment by plutonium-239** [comment]
You're right, but I leave that up to you

As for the current column width heuristic, is [this](https://github.com/YS-L/csvlens/blob/main/src/ui.rs#L71-L118) the function of interest?

**Comment by YS-L** [comment]
Yes, that is the function that determines column widths.

**Comment by YS-L** [comment]
Main branch should now handle this automatically. For example,

Before:
![before](https://github.com/user-attachments/assets/fb089bb8-8f50-4353-b46b-311d8527eb51)

After:
![after](https://github.com/user-attachments/assets/c8aced75-cabb-49f3-a9aa-afb6eca076b4)

Let me know if it works in your case.

**Comment by plutonium-239** [comment]
Can you make a patch/minor release with the latest code? (or is there one planned soon?)
I don't have cargo to build from source and am feeling a bit lazy😅(low on storage)

**Comment by YS-L** [comment]
Yes, I plan to make a release in about a week or so.

In the mean time, you can check out this CI run which builds the binaries with this change included: https://github.com/YS-L/csvlens/actions/runs/10019417514?pr=94.

Feel free to download the binary for your platform and try out. Appreciate any feedback!

**Comment by plutonium-239** [comment]
It works!

**Comment by luckman212** [comment]
Sorry for adding to a closed issue @YS-L , but I didn't want to open a new issue if this is user error. I'm using csvlens v0.13.0 (installed via Homebrew) on macOS. In my testing, even with not-very-wide columns, the columns are being truncated with plenty of horizontal space left in my terminal.

Example:

<img width="3958" height="2334" alt="Image" src="https://github.com/user-attachments/assets/4ae448e3-7e29-4319-b0c6-03eb460c3ac7" />

In that example screenshot, the last row of data is:
```
Sun 10:51am,192.168.20.107,10:f6:0a:a5:ab:a4,vgny-0f000z.vanguardcon.local.lan
```

My terminal width for that example was `204 x 50`

Is there a hidden flag to say "auto-expand all columns" or am I doing something else wrong here?

**Comment by plutonium-239** [comment]
Hmm, definitely something going wrong there. Do you have any script that can simulate these generated csvs/tsvs?

You could run `csvlens` with the `--debug` flag and share its output as well.

**Comment by YS-L** [comment]
Thanks @luckman212 for reporting this. Getting a blank table when piping data to csvlens is a bug so I've created #183 to track it. I have a theory about the cause: is there any chance the program generating the CSV takes a while before writing out any data?

Regarding the column widths issue, if you could share an example file, that would be helpful. Column widths should auto-expand by default, so if they don't, it could be a bug. Feel free to open a separate issue!

**Comment by luckman212** [comment]
@YS-L Happy holidays and thank you very much for this! I compiled from `main` and YES the stdin bug appears to be fixed now. I can no longer reproduce the issue. 👍 

As for the bug with the column widths/truncation I found out how to reproduce that and will open a separate issue.
