### ISSUE TITLE
Feature request: Auto-delimiter sniffing

### ISSUE THREAD

**Issue by jqnatividad** [YS-L/csvlens#9]
perhaps, with [csv-sniffer](https://github.com/jblondin/csv-sniffer)?

**Comment by egrieco** [comment]
See also [qsv-sniffer](https://github.com/jqnatividad/qsv-sniffer): CSV sniffer crate for Rust, optimized for qsv.

Pros:

> Its a detached fork of [csv-sniffer](https://github.com/jblondin/csv-sniffer) with these additional capabilities, detecting:
> 
> -   utf-8 encoding
> -   field names
> -   number of rows
> -   average record length
> -   additional data types - Date and DateTime

Caveats:

> ℹ️ **NOTE:** This fork is optimized to support [qsv](https://github.com/jqnatividad/qsv), and its development will be primarily dictated by qsv's requirements. Please continue to use `csv-sniffer` if you want a general-purpose CSV sniffer.

**Comment by YS-L** [comment]
I finally got to implementing this! Added this as an option `-d auto` in the main branch.
